version: '2.4'

services:
  nginx:
    image: nginx-react-app
    container_name: nginx-react-app
    build:
      context: frontend/
      dockerfile: Dockerfile  # Le Dockerfile pour construire l'app React et configurer Nginx
    ports:
      - "3000:80"
  
  node-api:
    image: node-api
    container_name: node-api
    build: 
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Assurez-vous que le conteneur expose bien l'API sur le port 80
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prom/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"  # Grafana is accessible on port 3001
    volumes:
      - ./data/grafana:/var/lib/grafana
  
  adminer:
    image: adminer
    container_name: postgres-database-ui
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: postgres-database
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    hostname: postgres
    volumes:
      - ./data/database:/var/lib/postgresql/data
      - ./config/db/init.sql:/docker-entrypoint-initdb.d/init.sql