version: '2.4'

services:

  react-app:
    image: react-app
    container_name: react-app
    build: 
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    
  # node-api:
  #   image: node-api
  #   container_name: node-api
  #   build: 
  #     context: backend/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"

  adminer:
    image: adminer
    container_name: postgres-database-ui
    restart: always
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    container_name: postgres-database
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  

volumes:
  postgres-data:
    name: database-volume-1
