version: '2.4'

services:

  react-app:
    image: react-app
    container_name: react-app
    build: 
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    
  node-api:
    image: node-api
    container_name: node-api
    build: 
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "80:80"

  adminer:
    image: adminer
    container_name: postgres-database-ui
    ports:
      - 8080:8080

  db:
    image: postgres
    container_name: postgres-database
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    hostname: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  

volumes:
  postgres-data:
    name: database-volume-1
