version: '2.4'

services:

  react-app:
    image: react-app
    container_name: react-app
    build: 
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    image: postgres
    restart: always
    container_name: postgres-database
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    container_name: postgres-database-ui
    ports:
      - 8080:8080


volumes:
  postgres-data:
    name: database-volume-1
