version: '3.8'

services:
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
      args:
        - API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    image: api
    container_name: api
    build: 
      context: api/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=username
      - DB_PASSWORD=password
      - DB_NAME=mydatabase
    depends_on:
      - database

  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - api
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - prometheus

  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - ./data/database:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"